export * from '@/pages/pagina-inicial/PaginaInicial'
export * from '@/pages/sobre/Sobre'
export * from '@/pages/projetos/Projetos'
export * from '@/pages/contato/Contato'
export * from '@/pages/formulario-enviado/FormEnviado'